language: node_js
sudo: required
dist: trusty
node_js:
  - 'stable'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - g++
      - google-chrome-stable

cache:
  directories:
    - node_modules
    - typings

install:
  - ./config/ci/install.sh

script:
  - ./config/ci/test.sh
